services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pm
    ports:
      - "5432:5432"
    networks:
      - pm-network
    volumes:
      - ./Scripts/exec.sql:/docker-entrypoint-initdb.d/scripts.sql
      - postgres-data:/var/lib/postgresql/data 
    restart: always

  project-manager:
    build:
      context: ./Aplicação
      dockerfile: ProjectManagerApi/Dockerfile
    container_name: projectManager
    ports:
      - "5000:8080"
    networks:
      - pm-network
    restart: always
volumes:
  postgres-data:
  mongo_data:

networks:
  pm-network:
    external: true